default: client_PC

client_PC: client_PC.c
	cc -lm -Wall -o client_PC client_PC.c
clean:
	rm -f client_PC *.xg



#default: serv_tcp client_tcp

#serv_tcp: serv_tcp.c
#	cc -Wall -D_REENTRANT -o serv_tcp serv_tcp.c -pthread

#client_tcp: client_tcp.c
#	cc -Wall -o client_tcp client_tcp.c
#clean:
#	rm -f serv_tcp client_tcp
